export interface CustomerRecord {
  customerID: string;
  gender: string;
  seniorCitizen: number;
  partner: string;
  dependents: string;
  tenure: number;
  phoneService: string;
  multipleLines: string;
  internetService: string;
  onlineSecurity: string;
  onlineBackup: string;
  deviceProtection: string;
  techSupport: string;
  streamingTV: string;
  streamingMovies: string;
  contract: string;
  paperlessBilling: string;
  paymentMethod: string;
  monthlyCharges: number;
  totalCharges: number;
  churn: number;
}

export const rawDataset: CustomerRecord[] = [
  { customerID:"7590-VHVEG", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:1, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:29.85, totalCharges:29.85, churn:0 },
  { customerID:"5575-GNVDE", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:34, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:56.95, totalCharges:1889.5, churn:0 },
  { customerID:"3668-QPYBK", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Mailed check", monthlyCharges:53.85, totalCharges:108.15, churn:1 },
  { customerID:"7795-CFOCW", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:45, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:42.30, totalCharges:1840.75, churn:0 },
  { customerID:"9237-HQITU", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.70, totalCharges:151.65, churn:1 },
  { customerID:"9305-CDSKC", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:8, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:99.65, totalCharges:820.50, churn:1 },
  { customerID:"1452-KIOVK", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:22, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:89.10, totalCharges:1949.40, churn:0 },
  { customerID:"6713-OKOMC", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:10, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:29.75, totalCharges:301.90, churn:0 },
  { customerID:"7892-POOKP", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:28, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:104.80, totalCharges:3046.05, churn:1 },
  { customerID:"6388-TABGU", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:62, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:56.15, totalCharges:3487.95, churn:0 },
  { customerID:"9763-GRSKD", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:13, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Mailed check", monthlyCharges:49.95, totalCharges:587.45, churn:0 },
  { customerID:"7469-LKBCI", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:16, phoneService:"Yes", multipleLines:"No", internetService:"No", onlineSecurity:"No internet service", onlineBackup:"No internet service", deviceProtection:"No internet service", techSupport:"No internet service", streamingTV:"No internet service", streamingMovies:"No internet service", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:18.95, totalCharges:326.80, churn:0 },
  { customerID:"8091-TTVAX", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:58, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:100.35, totalCharges:5681.10, churn:0 },
  { customerID:"0280-XJGEX", gender:"Male", seniorCitizen:1, partner:"No", dependents:"No", tenure:49, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:103.70, totalCharges:5036.30, churn:1 },
  { customerID:"5129-JLPIS", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:25, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:105.50, totalCharges:2452.00, churn:1 },
  { customerID:"3655-SNQYZ", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:39, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:102.95, totalCharges:4183.00, churn:1 },
  { customerID:"8191-XWSZG", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:69.65, totalCharges:151.65, churn:1 },
  { customerID:"9959-WOFKT", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:68, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:100.35, totalCharges:6600.00, churn:0 },
  { customerID:"4190-MFLUW", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:72, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:84.65, totalCharges:6043.80, churn:0 },
  { customerID:"4183-MYFRB", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:53, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:94.25, totalCharges:5039.00, churn:1 },
  { customerID:"6713-RSVEE", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:45, phoneService:"Yes", multipleLines:"Yes", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:69.65, totalCharges:3213.60, churn:0 },
  { customerID:"2034-NMAEH", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Mailed check", monthlyCharges:54.65, totalCharges:107.75, churn:1 },
  { customerID:"8788-JMFRC", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:9, phoneService:"Yes", multipleLines:"Yes", internetService:"No", onlineSecurity:"No internet service", onlineBackup:"No internet service", deviceProtection:"No internet service", techSupport:"No internet service", streamingTV:"No internet service", streamingMovies:"No internet service", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:24.10, totalCharges:215.20, churn:0 },
  { customerID:"3044-NWSMJ", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.35, totalCharges:70.35, churn:1 },
  { customerID:"4801-JZAZL", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:60.55, totalCharges:4320.00, churn:0 },
  { customerID:"8361-LTMKD", gender:"Male", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:4, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Mailed check", monthlyCharges:74.40, totalCharges:306.60, churn:1 },
  { customerID:"3186-AJIEK", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:72, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:118.75, totalCharges:8670.10, churn:0 },
  { customerID:"9763-GRSKD", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:69.70, totalCharges:69.70, churn:1 },
  { customerID:"5354-WDSIL", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:71, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"No", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:80.85, totalCharges:5737.50, churn:0 },
  { customerID:"5955-OYZRK", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.00, totalCharges:150.30, churn:1 },
  { customerID:"0567-XRHCU", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:70, phoneService:"Yes", multipleLines:"Yes", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:89.15, totalCharges:6369.10, churn:0 },
  { customerID:"9737-DWXHC", gender:"Male", seniorCitizen:1, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:80.65, totalCharges:80.65, churn:1 },
  { customerID:"7892-POOKP", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:36, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:64.20, totalCharges:2308.50, churn:0 },
  { customerID:"6388-TABGU", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:3, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.35, totalCharges:211.75, churn:1 },
  { customerID:"2236-ITMNJ", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:12, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:79.00, totalCharges:962.20, churn:0 },
  { customerID:"4960-QLPCO", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:52, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:80.15, totalCharges:4259.25, churn:0 },
  { customerID:"3714-BQNYV", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:79.65, totalCharges:160.15, churn:1 },
  { customerID:"5239-HIFRS", gender:"Female", seniorCitizen:1, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Mailed check", monthlyCharges:69.95, totalCharges:69.95, churn:1 },
  { customerID:"1699-UIPMW", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:61, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:46.10, totalCharges:2886.25, churn:0 },
  { customerID:"7990-CFHDO", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:22, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:70.40, totalCharges:1533.90, churn:0 },
  { customerID:"8945-GGKWI", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:10, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:80.65, totalCharges:803.15, churn:1 },
  { customerID:"1769-UINLG", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:13, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:88.15, totalCharges:1121.00, churn:1 },
  { customerID:"4926-BWHWH", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:20.35, totalCharges:20.35, churn:1 },
  { customerID:"8744-UIUQK", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:115.50, totalCharges:8312.00, churn:0 },
  { customerID:"3827-TMLTU", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:14, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:90.80, totalCharges:1285.35, churn:0 },
  { customerID:"3827-TMLTU", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:69.50, totalCharges:69.50, churn:1 },
  { customerID:"9924-AWPOT", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:68, phoneService:"Yes", multipleLines:"No", internetService:"No", onlineSecurity:"No internet service", onlineBackup:"No internet service", deviceProtection:"No internet service", techSupport:"No internet service", streamingTV:"No internet service", streamingMovies:"No internet service", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:19.65, totalCharges:1300.65, churn:0 },
  { customerID:"4079-ASDNP", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:36, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:79.65, totalCharges:2880.15, churn:1 },
  { customerID:"9999-WJPMB", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:70, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:100.75, totalCharges:7051.70, churn:0 },
  { customerID:"1234-ABCDE", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:75.20, totalCharges:75.20, churn:1 },
  { customerID:"2345-BCDEF", gender:"Male", seniorCitizen:1, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:84.50, totalCharges:169.00, churn:1 },
  { customerID:"3456-CDEFG", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:60, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:68.40, totalCharges:4080.00, churn:0 },
  { customerID:"4567-DEFGH", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:3, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:90.45, totalCharges:271.35, churn:1 },
  { customerID:"5678-EFGHI", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:48, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"Yes", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:105.15, totalCharges:5047.20, churn:1 },
  { customerID:"6789-FGHIJ", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:54.50, totalCharges:3924.00, churn:0 },
  { customerID:"7890-GHIJK", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:5, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:69.75, totalCharges:348.75, churn:1 },
  { customerID:"8901-HIJKL", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:29, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:45.25, totalCharges:1312.25, churn:0 },
  { customerID:"9012-IJKLM", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:15, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:79.80, totalCharges:1197.00, churn:0 },
  { customerID:"0123-JKLMN", gender:"Male", seniorCitizen:1, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.10, totalCharges:70.10, churn:1 },
  { customerID:"1234-KLMNO", gender:"Female", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:55, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"One year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:59.65, totalCharges:3280.75, churn:0 },
  { customerID:"2345-LMNOP", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:4, phoneService:"No", multipleLines:"No phone service", internetService:"DSL", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:25.10, totalCharges:100.40, churn:1 },
  { customerID:"3456-MNOPQ", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:66, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:113.85, totalCharges:7514.10, churn:0 },
  { customerID:"4567-NOPQR", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.85, totalCharges:70.85, churn:1 },
  { customerID:"5678-OPQRS", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:35, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:100.00, totalCharges:3500.00, churn:1 },
  { customerID:"6789-PQRST", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"No", internetService:"No", onlineSecurity:"No internet service", onlineBackup:"No internet service", deviceProtection:"No internet service", techSupport:"No internet service", streamingTV:"No internet service", streamingMovies:"No internet service", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:19.75, totalCharges:1422.00, churn:0 },
  { customerID:"7890-QRSTU", gender:"Female", seniorCitizen:1, partner:"No", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.00, totalCharges:140.00, churn:1 },
  { customerID:"8901-RSTUV", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:41, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:60.35, totalCharges:2474.35, churn:0 },
  { customerID:"9012-STUVW", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:6, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:84.95, totalCharges:509.70, churn:1 },
  { customerID:"0123-TUVWX", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:110.50, totalCharges:7956.00, churn:0 },
  { customerID:"1234-UVWXY", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:3, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:90.25, totalCharges:270.75, churn:1 },
  { customerID:"2345-VWXYZ", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:60, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:64.55, totalCharges:3873.00, churn:0 },
  { customerID:"9001-ABCDE", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:7, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:79.95, totalCharges:559.65, churn:1 },
  { customerID:"9002-BCDEF", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"No", paymentMethod:"Credit card (automatic)", monthlyCharges:115.80, totalCharges:8337.60, churn:0 },
  { customerID:"9003-CDEFG", gender:"Male", seniorCitizen:1, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.45, totalCharges:70.45, churn:1 },
  { customerID:"9004-DEFGH", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:31, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"No", paymentMethod:"Mailed check", monthlyCharges:46.70, totalCharges:1447.70, churn:0 },
  { customerID:"9005-EFGHI", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:2, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:85.00, totalCharges:170.00, churn:1 },
  { customerID:"9006-FGHIJ", gender:"Female", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:65, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:65.10, totalCharges:4231.50, churn:0 },
  { customerID:"9007-GHIJK", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:4, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:80.00, totalCharges:320.00, churn:1 },
  { customerID:"9008-HIJKL", gender:"Female", seniorCitizen:1, partner:"No", dependents:"No", tenure:52, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:104.50, totalCharges:5434.00, churn:1 },
  { customerID:"9009-IJKLM", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"No", internetService:"No", onlineSecurity:"No internet service", onlineBackup:"No internet service", deviceProtection:"No internet service", techSupport:"No internet service", streamingTV:"No internet service", streamingMovies:"No internet service", contract:"Two year", paperlessBilling:"No", paymentMethod:"Bank transfer (automatic)", monthlyCharges:20.15, totalCharges:1450.80, churn:0 },
  { customerID:"9010-JKLMN", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:8, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:69.80, totalCharges:558.40, churn:1 },
  { customerID:"9011-KLMNO", gender:"Male", seniorCitizen:0, partner:"No", dependents:"No", tenure:44, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"No", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"One year", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:51.85, totalCharges:2281.40, churn:0 },
  { customerID:"9012-LMNOP", gender:"Female", seniorCitizen:1, partner:"Yes", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.25, totalCharges:70.25, churn:1 },
  { customerID:"9013-MNOPQ", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"Yes", tenure:56, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"No", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"No", streamingMovies:"No", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:99.85, totalCharges:5591.60, churn:0 },
  { customerID:"9014-NOPQR", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:1, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:70.00, totalCharges:70.00, churn:1 },
  { customerID:"9015-OPQRS", gender:"Male", seniorCitizen:0, partner:"Yes", dependents:"No", tenure:27, phoneService:"Yes", multipleLines:"No", internetService:"DSL", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"No", techSupport:"No", streamingTV:"Yes", streamingMovies:"No", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Credit card (automatic)", monthlyCharges:62.35, totalCharges:1683.45, churn:0 },
  { customerID:"9016-PQRST", gender:"Female", seniorCitizen:0, partner:"No", dependents:"No", tenure:3, phoneService:"Yes", multipleLines:"No", internetService:"Fiber optic", onlineSecurity:"No", onlineBackup:"No", deviceProtection:"No", techSupport:"No", streamingTV:"No", streamingMovies:"Yes", contract:"Month-to-month", paperlessBilling:"Yes", paymentMethod:"Electronic check", monthlyCharges:79.90, totalCharges:239.70, churn:1 },
  { customerID:"9017-QRSTU", gender:"Male", seniorCitizen:0, partner:"No", dependents:"Yes", tenure:72, phoneService:"Yes", multipleLines:"Yes", internetService:"Fiber optic", onlineSecurity:"Yes", onlineBackup:"Yes", deviceProtection:"Yes", techSupport:"Yes", streamingTV:"Yes", streamingMovies:"Yes", contract:"Two year", paperlessBilling:"Yes", paymentMethod:"Bank transfer (automatic)", monthlyCharges:119.00, totalCharges:8568.00, churn:0 },
];
